#!/bin/sh
exitCode=0;

cleanTranlog(){
        path="/opt/tranlog/$1/tranlog"
        if [ -d ${path} ]; then
          /opt/tranlog/cleanTranslog.sh $path
          status=$?
          if [[ ${status} -gt 0 ]]; then
                echo "Alert: Translog cleanup of ${path} failed with exitcode=${status}"
                exitCode=${status}
          fi;
        fi
}
cleanLogFiles(){
          # Set the target directory
        TARGET_DIR="/logs"
        if [ -d "$TARGET_DIR" ]; then
                # Find and remove empty directories older than 14 days, and print the actions to stdout
                find "$TARGET_DIR" -type d -name "*.snapshot*" -prune -o -type d -mtime +14 -exec sh -c  'echo "Removing directory: $1"; rmdir --ignore-fail-on-non-empty "$1" || echo "Error removing directory: $1"' _ {} \;

                # Find and remove files older than 14 days, and print the actions to stdouti
                find "$TARGET_DIR" -type d -name "*.snapshot*" -prune -o -type f -mtime +14 -exec sh -c 'echo "Removing file: $1"; rm -f "$1" || echo "Error removing file: $1"' _ {} \;
                status=$?
                if [[ ${status} -gt 0 ]]; then
                        echo "Alert: Logs cleanup of ${TARGET_DIR} failed with exitcode=${status}"
                        exitCode=${status}
                fi;
        fi
}


cleanTranlog qm0
cleanTranlog qm1
cleanTranlog qm2
cleanTranlog qm3

cleanLogFiles

:
echo "exitcode: ${exitCode}"
exit ${exitCode}


#!/bin/sh
if [ ! -d "$1/leases/opf-group" ]; then
  echo "leases/opf-group does not exist, cleanup aborted"
  exit 1
fi

echo BaseDir=$1

for dir in $1/tl-* ; do
    leaseFileName=$(echo "$dir" | cut -d "/" -f6 | sed "s/^tl//" )
    leaseFileName=$(echo "$leaseFileName" | sed "s/[-]//g")
    leasesFilePath="$1/leases/opf-group/$leaseFileName"
    echo Directory=$dir
    echo LeasesFilePath=$leasesFilePath
    if [ ! -f "$leasesFilePath" ]; then
        if [ -z "$(ls -A $dir/partnerlog )" ] && [ -z "$(ls -A $dir/tranlog )" ];  then
           echo "REMOVED: $dir / $leaseFileName -  does not exist in leases folder, can be removed"
           rm -rv "$dir"
        else
           echo "WARN: Trans Log $dir is NOT Empty but has no Lease File $leaseFileName"
        fi
    else
       if [ ! -s "$leasesFilePath" ]; then
          echo "ERROR: Leasefile $leaseFileName is a zero byte file"
       else
          echo "NOT REMOVED: $dir / $leaseFileName -  exist in leases folder, can not be removed"
       fi
    fi
done


Issues
1.	The directory that the lease file points to does not contain a tranlog or a partnerlog sub directory 
2.	The directory that the lease file points to does not contain a tranlog sub directory
3.	The directory that the lease file points to does contain a tranlog sub directory but that directory is empty
4.	The directory that the lease file points to does not contain a partnerlog sub directory
5.	The directory that the lease file points to does contain a partnerlog sub directory but that directory is empty


Actions the script should take for each issue
1.	Delete the lease file and the folder it points at.
2.	Delete the lease file and the folder it points at.
3.	Delete the lease file and the folder it points at.
4.	Echo out a message but no not delete anything
5.	Echo out a message but no not delete anything



Issues : 
1.	The directory that the lease file points to does not contain a tranlog or a partnerlog sub directory 
2.	The directory that the lease file points to does contain a tranlog sub directory but that directory is empty
3.	The directory that the lease file points to does contain a partnerlog sub directory but that directory is empty

Actions :
1.	Delete the lease file and the folder it points at.
2.	Delete the lease file and the folder it points at.
3.	Echo out a message but no not delete anything


Final - 

#!/bin/sh

if [ ! -d "$1/leases/opf-group" ]; then
  echo "leases/opf-group does not exist, cleanup aborted"
  exit 1
fi

echo BaseDir=$1

for dir in $1/tl-*; do
    leaseFileName=$(echo "$dir" | cut -d "/" -f6 | sed "s/^tl//")
    leaseFileName=$(echo "$leaseFileName" | sed "s/[-]//g")
    leasesFilePath="$1/leases/opf-group/$leaseFileName"

    echo Directory=$dir
    echo LeasesFilePath=$leasesFilePath

    if [ ! -f "$leasesFilePath" ]; then
        if [ -z "$(ls -A $dir/partnerlog)" ] && [ -z "$(ls -A $dir/tranlog)" ]; then
            echo "REMOVED: $dir / $leaseFileName - does not exist in leases folder, can be removed"
            # Delete the directory and its contents
            rm -rv "$dir"
        else
            echo "WARN: Trans Log $dir is NOT Empty but has no Lease File $leaseFileName"
        fi
    else
        if [ ! -d "$dir/tranlog" ] && [ ! -d "$dir/partnerlog" ]; then
            echo "REMOVED: $dir / $leaseFileName - does not contain tranlog or partnerlog, deleting"
            # Delete the directory and its contents
            rm -rv "$dir"
        elif [ -d "$dir/tranlog" ] && [ -z "$(ls -A $dir/tranlog)" ]; then
            echo "REMOVED: $dir / $leaseFileName - tranlog is empty, deleting"
            # Delete the directory and its contents
            rm -rv "$dir"
        elif [ -d "$dir/partnerlog" ] && [ -z "$(ls -A $dir/partnerlog)" ]; then
            echo "WARN: $dir / $leaseFileName - partnerlog is empty, no deletion"
            # Echo a warning message, no deletion
        else
            echo "NOT REMOVED: $dir / $leaseFileName - exists in leases folder, cannot be removed"
            # Echo a message, no deletion
        fi
    fi
done
